[package]
name = "epics"
version = "0.1.0"
edition = "2021"

[dependencies]
mio = { version = "1.0.3", features = ["net", "os-poll"] }
nom = "8.0.0"
pnet = { version = "0.35.0", default-features = false, features = ["pnet_datalink", "std"] }
